// Generates the global AI-readable Markdown index for the whole site (plan §18).
//
// One file — public/llms.md — describing the notebook and listing every notebook
// page with a clean title, a stable link and an optional short description. It is
// meant for external AI systems and normal web tools to navigate the public site.
//
// The notebook collection itself lives in Firestore under each user's private
// subtree, so this index describes the public application shell and is refreshed
// as part of a deploy. Run it before deploying: `npm run sync-public`.

import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const out = join(root, "public", "llms.md");

const SITE = {
  title: "DSA Notebook",
  url: "https://dsa-notebook-e65d2.web.app",
  description:
    "A personal DSA (data structures and algorithms) learning notebook. Write problem " +
    "notes in Markdown, connect problems by pattern with tags, search every notebook " +
    "instantly, and revise with active recall, spaced repetition and a mistake log.",
};

const PAGES = [
  { path: "/", title: "DSA Notebook — the notebook editor", desc: "Block editor with headings, Markdown text, code blocks, images and sandboxed visuals. Notebooks live in folders; changes autosave to the cloud and work offline." },
  { path: "/#dashboard", title: "Dashboard", desc: "Continue where you left off, recently edited notebooks, what is due today, weak topics and mistakes to review." },
  { path: "/#tags", title: "Tags / pattern index", desc: "Every tag (two-pointers, sliding-window, binary-search, hashing, greedy …) with the notebooks that carry it." },
  { path: "/#revise", title: "Revision", desc: "Daily scheduled reviews, tag/state-based sessions, mixed interleaved practice and mistake-focused sessions." },
];

const lines = [
  `# ${SITE.title} — AI index`,
  "",
  `> ${SITE.description}`,
  "",
  "## About this site",
  "",
  `- **URL:** ${SITE.url}`,
  `- **Purpose:** store DSA knowledge, retrieve it fast, revise it intelligently, connect problems and patterns, and learn from mistakes.`,
  `- **Content model:** one notebook per problem/topic. Notebooks are grouped into folders and tagged with DSA patterns.`,
  `- **Structure of a good problem note:** Problem · Pattern/Trigger · Key Observation · Invariant · Approach · Example/Dry Run · Code · Complexity · Edge Cases · Mistake/Pitfall · Remember · Related Problems.`,
  "",
  "## Pages",
  "",
  ...PAGES.map((p) => `- [${p.title}](${SITE.url}${p.path}) — ${p.desc}`),
  "",
  "## How an AI or crawler should use this",
  "",
  "1. Start at the root URL above — it is the app shell and loads the notebook collection.",
  "2. Each notebook is a Markdown document; use the in-app search (Ctrl+F) or the tag index to locate one.",
  "3. The exported Markdown form of any notebook preserves headings, fenced code and links, so downstream tooling can parse it directly.",
  "",
  "_This file is generated by `npm run sync-public` and refreshed on deploy._",
  "",
];

mkdirSync(join(root, "public"), { recursive: true });
writeFileSync(out, lines.join("\n"), "utf8");
console.log("wrote " + out);
